### ISSUE TITLE
bind-keys?

### ISSUE THREAD

**Issue by kaushalmodi** [GuiltyDolphin/emaps#4]
Out of curiosity, how does this package compare to [`bind-keys`](https://github.com/jwiegley/use-package/blob/master/bind-key.el) (which is part of the [`use-package`](https://github.com/jwiegley/use-package) package)?

Below is an example of bindings added to `dired-mode-map` using `bind-keys`. The example is taken from the `bind-keys.el` Commentary.

``` el
(bind-keys :map dired-mode-map
  ("o" . dired-omit-mode)
  ("a" . some-custom-dired-function))
```

**Comment by GuiltyDolphin** [comment]
@kaushalmodi In terms of defining keys (at least currently), `emaps` just offers a replacement for the standard `define-key` that allows you to define multiple keys simultaneously. I may add some additional 'meta' functionality for this at some point (such as tracking bindings).

In terms of _displaying_ keymaps, `bind-key` offers a way of viewing keybindings made with `bind-key`; `emaps` does not have an equivalent (at least, not at the moment), but it does have `emaps-describe-keymap-bindings` which will (prettily) display any keymap (with intelligent completion).

I'm hoping to add more features in the future (currently working on reading keys w/ defaults), so if you have any suggestions please don't hesitate to throw them my way :smile:

**Comment by kaushalmodi** [comment]
Thanks for the reply. 

`bind-key`/`bind-key*`/`bind-keys`/`bind-keys*` offer a way to define single/multiple bindings, enable tracking bindings made using these macros, and many more features.

The question is: What extra features does `emaps` offer over `bind-keys`? Given many people use `use-package`, they already have `bind-keys.el` installed. Why would they install `emaps` too? 

If you think in that direction, if you have features that can build upon `bind-keys`, it would be nice if you made contributions to that package.

Just my few cents.

**Comment by GuiltyDolphin** [comment]
@kaushalmodi I'm not really heading in the direction of bind-keys (to my knowledge, anyway); as far as I understand, `bind-keys` is about improving _personal_ keybindings - those you would declare in your init config.

I'm not aiming for super-powerful keybinding specification, with Emaps I'm aiming to provide keymap (and key binding) _utilites_, not aimed just at users, but at packages (or any scripts) that might need them too.

There admittedly is an overlap in the `emaps-define-key`/`bind-key` (though I believe `bind-key` will do a lot more); it's just a common thing to have to use `define-key` over and over (have you seen [this](https://github.com/bonega/evil/blob/master/evil-maps.el#L32) for example?), so that just aims to make those definitions a bit shorter.

If I come up with any amazing ideas for better improving your personal bindings, sure, `bind-keys` is probably a good place for it - but general utilities? I don't think that's the right place.

One of the current features I'm working on is reading and identifying keys and key sequences, and providing a more comprehensive prompting/read for these. 

Thanks for the feedback - I really appreciate it.

**Comment by 4goodapp** [comment]
@GuiltyDolphin 
Just wanted to thanks you for this package.
I am new to "Emacs" and was searching/looking for a way to do EXACTLY what `emaps-describe-keymap-bindings` does.

Question, Are you still working on this package?

**Comment by GuiltyDolphin** [comment]
@4goodapp 

> Just wanted to thanks you for this package.

Thank you! It's great to know that I'm able to help in some way :)

> Question, Are you still working on this package?

Yes! I maintain [several packages for Emacs](https://github.com/GuiltyDolphin?tab=repositories&type=source&language=emacs+lisp), some more actively developed than others. I regularly use `emaps-describe-keymap-bindings` ([I've bound it to `C-h K`](https://github.com/GuiltyDolphin/dotfiles/blob/master/dotfiles/emacs/custom/config.org#emaps)) and use `emaps-define-key` a fair bit in [my config](https://github.com/GuiltyDolphin/dotfiles/blob/master/dotfiles/emacs/custom/config.org#helm).

However, ~I haven't had many "Oh, I should really add that to emaps!" moments recently...~ If you have any suggestions/requests/contributions, please do create an issue so we can discuss it!

EDIT: I've had a quick look over the code, and existing issues, and I've had a few more ideas that should improve and add to emaps' functionality :)

**Comment by 4goodapp** [comment]
GREAT! :)
I currently have any issue though.

**Comment by GuiltyDolphin** [comment]
I'm closing this issue based on existing discussion.

To summarise: `emaps` and `bind-keys` have different purposes and different approaches.

`bind-keys` is more about personalisation, making it easy to define new bindings and view your personalised bindings.

`emaps` is about utility: a (currently fairly minimal) library for working with keymaps, including viewing existing keymaps (not just your own bindings) and binding new keys. Hopefully in the future I'll be able to open up some more of the API to provide more of the functions used internally (e.g., checking if a keymap is active).


If you have anything else to add, or further questions, feel free to comment on this issue, or open a new issue if you feel it is appropriate.
